// external declaration of sound table:

extern far cdata SNDTBL_STARTREKSOUNDS;

// external declarations of addresses of sounds for direct access:

extern far cdata SX_alarm1_shipWideAlert;
extern far cdata SX_inputok2_inputSuccessful;
extern far cdata SX_phasertype2_phaserTypeIII;
extern far cdata SX_photorp3;
extern far cdata SX_shieldraise;
extern far cdata SX_voiceinput1_readyForInput1;

// constants defining sounds as entries in the sound table:

#define SND_alarm1_shipWideAlert 1
#define SND_inputok2_inputSuccessful 2
#define SND_phasertype2_phaserTypeIII 3
#define SND_photorp3            4
#define SND_shieldraise         5
#define SND_voiceinput1_readyForInput1 6

